# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Redox'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["redox_left","redox_right"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'

      